#!/usr/bin/env ruby
# This command will automatically be run when you run "rails" with Rails gems
# installed from the root of your application.

APP_PATH = File.expand_path('../../../../spec/dummy/config/application', __dir__)

require 'rails/all'
